### ISSUE TITLE
Allow api to start without MongoDB

### ISSUE THREAD

**Issue by Mystaken** [TeamHarrington/code-reviewer#11]
We need the back-end to be able to start without MongoDB because any changes in the GraphQL schemas in back-end requires front-end people to start the back-end (Just to update front-end schemas). Many of them do not need to make any other request.

- Back-end should be able to start without MongoDB (in `development` mode only)
- If request (GraphQL or REST) is made without MongoDB on, return error response with status 500.

**Comment by BoZhaoUTSC** [comment]
Shall we use a cloud mongodb like mlab for this?
We can setup a simple db with read only access for some quick and simple development. And setup a db with write permission for slightly complicated development.

**Comment by Mystaken** [comment]
We can, but often times, the front-end people don't need to fully start the back-end, since I'm guessing the components will be built via Storybook. We just need to start it to update the GraphQL schemas.

**Comment by BoZhaoUTSC** [comment]
I found a new & better solution for this. Using JSON server to watch a local JSON file is a better optional comparing to using mLab.
